kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraVolumes:
      - name: custom-apiserver
        hostPath: /usr/local/bin/kube-apiserver-custom
        mountPath: /usr/local/bin/kube-apiserver
        readOnly: true
  extraMounts:
  - hostPath: /Users/md007711/Desktop/dev-projects/kubernetes/_output/local/bin/linux/arm64/kube-apiserver
    containerPath: /usr/local/bin/kube-apiserver-custom
